### ISSUE TITLE
Dev Focused article on how to send and receive payment using Chimoney

### ISSUE THREAD

**Issue by Hauwarh** [Chimoney/chimoney-community-projects#32]
- [x] Sending payment using Chimoney
- [x] Receiving payment using Chimoney

**Comment by adi-uchiha** [comment]
I would like to write this

**Comment by knight-95** [comment]
i would like to work upon this, I am familiar with web3 and have used Chingari wallet in past

**Comment by Aysha-py** [comment]
@uchibeke Hi, Is this issue still open to be contributed to? I will love to work on it.

**Comment by uchibeke** [comment]
@adi-uchiha, @Aysha-py and @knight-95 please yes go for it

Articles from all of you are welcome. Please try to send them in before end of hacktoberfest

**Comment by Aysha-py** [comment]
@uchibeke Sure, thanks

**Comment by Aysha-py** [comment]
@uchibeke, is there a way I could interact with the chimoney platform to initiate payment and receive it in order to get some screenshots for my article? 
I read an article on hashnode on how you can create an organization on the chimoney dashboard after signing up, then join the discord server so that you can be approved. However, after clicking the discord link I get feedback saying the invite may have expired or I don't have permission to join.

**Comment by GloriaOkeke** [comment]
Hi @uchibeke can I also work on this please?
